# Project information
site_name: docs.rajandangi
site_url: https://docs.rajandangi.com.np
site_author: Rajan Dangi
site_description: >-
  Development documentation for Rajan Dangi.

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrateÏ
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg
  logo: assets/logo.svg
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - includes

plugins:
  - search
  - blog:
      post_url_format: "{categories}/{slug}"
      post_date_format: long

# Repository
repo_name: squidfunk/mkdocs-material
repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: "Copyright &copy; 2025 Rajan Dangi"

# Page tree
nav:
  - Home: index.md
  - JavaScript:
      - javascript/index.md
      - How JavaScript Works: javascript/how-javascript-works.md
      - Execution Context & Call Stack: javascript/javascript-call-stack.md
      - Hoisting: javascript/hoisting.md
      - Function invocation and Variable Environment: javascript/function-invocation-and-variable-environment.md
      - this Keyword: javascript/this-keyword.md
      - undefined vs not defined: javascript/undefined-vs-not-defined.md
      - javascript/loosely-typed-language.md
      - JavaScript Scopes:
          - javascript/scope-chain-scope-lexical-environment.md
          - javascript/let-const-and-Temporal-Dead-Zone.md
          - javascript/block-scope-function-scope-shadowing.md
      - Closures in JavaScript:
          - Foundation: javascript/closures.md
          - javascript/setTimeout-and-closures.md
          - javascript/closure-interview-questions.md
      - Advanced JS Concepts:
          - javascript/first-class-functions.md
          - javascript/callback-functions.md
          - javascript/async-js-and-event-loop.md
          - javascript/js-engine-architecture.md
          - javascript/higher-order-functions.md
          - javascript/map-filter-reduce.md
          - javascript/callback-hell.md
          - javascript/promises.md
          - javascript/promises-async-await.md
          - javascript/promise-apis-all-allsettled-race-any.md
          - javascript/call-apply-bind.md
          - javascript/bind-polyfill.md
          - javascript/function-currying.md
          - javascript/debouncing-throttling.md
          - javascript/event-deligation.md
  - React:
      - react/index.md
      - Inception: react/inception.md
      - Igniting our app: react/ignition.md
      - Laying the foundation: react/laying-the-foundation.md
      - Talk is cheap, show me the code: react/talk-is-cheap-show-me-the-code.md
      - Let's Get Hooked: react/lets-get-hooked.md
      - Exploring the World: react/exploring-the-world.md
      - Finding the Path: react/finding-the-path.md
      - Let's Get Classy: react/lets-get-classy.md
      - Optimizing our app: react/optimizing-our-app.md
      - Show it to the world: react/show-it-to-the-world.md
      - Data is the new oil: react/data-is-the-new-oil.md
      - Let's Build Our Store: react/lets-build-our-store.md
      - Time for Test: react/time-for-test.md
      - useRef Hook: react/useRef-hook.md
  - PHP:
      - php/index.md
      - Dependency Injection (DI): php/dependency-injection.md
      - Inversion of Control (IoC): php/inversion-of-control.md
  - Blog:
      - blog/index.md
      - Download protected pdf from google drive: blog/posts/download-protected-pdf-from-google-drive.md

  - Community:
      - Contributing:
          - contributing/index.md
          - Reporting a bug: contributing/reporting-a-bug.md
          - Reporting a docs issue: contributing/reporting-a-docs-issue.md

  - Reference:
      - reference/index.md
