authors:
  rajandangi:
    name: Rajan Dangi        # Author name
    description: Creator # Author description
    avatar: https://avatars.githubusercontent.com/u/42113582?v=4         # Author avatar
    url: https://github.com/squidfunk            # Author website URL